# Generated by Django 3.1.7 on 2021-05-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=25, null=True)),
                ('lastName', models.CharField(blank=True, max_length=25, null=True)),
                ('Company', models.CharField(default='General', max_length=50)),
                ('contact_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRM.customers')),
            ],
        ),
        migrations.CreateModel(
            name='addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('home', 'home'), ('office', 'office'), ('billing', 'billing'), ('shipping', 'shipping')], default='home', max_length=10)),
                ('firstLine', models.CharField(max_length=50)),
                ('secondline', models.CharField(blank=True, max_length=50, null=True)),
                ('Block', models.CharField(max_length=25)),
                ('District', models.CharField(max_length=25)),
                ('State', models.CharField(max_length=25)),
                ('pin', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.customers')),
            ],
        ),
    ]
