# Generated by Django 3.1.7 on 2021-05-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CRM', '0001_initial'),
        ('display_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_Orders_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default='0')),
                ('total_value', models.PositiveIntegerField()),
                ('tax', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='display_app.products')),
                ('Sales_Order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRM.sales_orders')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_qty', models.IntegerField(default='0')),
                ('Availablity_status', models.CharField(choices=[('Available', 'Available'), ('Below Reorder level', 'Below_Reorder_level'), ('Out of Stock', 'Out_of_Stock')], default='Out of Stock', max_length=19)),
                ('reorder_level', models.PositiveSmallIntegerField(default='2')),
                ('target_level', models.PositiveIntegerField(default='10')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='display_app.products')),
            ],
        ),
    ]
